name: savegaza
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/ic_launcher.png"
